spring:
  datasource:
    url: jdbc:postgresql://10.140.0.3:5432/postgresql
#    url: jdbc:postgresql://localhost:5432/postgresql
    username: postgresql
    password: postgrespassword
  jpa:
    show-sql: false # jpa query 로그 안남김
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
  rabbitmq:
    host: 10.178.0.14
    username: guest
    password: guest
    port: 5672
server:
  port: 8080